# Generated by Django 6.0.5 on 2026-05-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
