# Generated by Django 6.0.5 on 2026-05-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_owner_cover_notes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.userprofile'),
        ),
    ]
